config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks' }
  root 'pages#index'
  get 'discourse/sso', to: 'discourse#sso'

  resources :repositories, only: [:index, :show] do
    resources :issues, only: [:index, :show] do
      resources :comments, only: :index
    end
  end

  resources :projects

  get '/marketplace', to: 'pages#marketplace', as: 'marketplace'
  get '/u/:username', to: 'pages#public_profile', as: 'public_profile'
  get '/u/:username/repositories', to: 'repositories#scoped_repositories', as: 'scoped_repositories'
  get '/u/:username/:repository', to: 'repositories#show_scoped_repositories', as: 'scoped_repository'
  get '/settings/profile', to: 'pages#profile', as: 'profile'
  post '/payload', to: 'github#payload', as: 'payload'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :repository
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :user
  belongs_to :repository
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :issue, optional: true
  belongs_to :user, optional: true
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :repository
  belongs_to :user, optional: true
  has_many :comments
  scope :open, -> { where(state: 'open') }
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :projects
  acts_as_taggable
end

app/models/project.rb
class Project < ApplicationRecord
  enum category: [:op1, :op2, :op3]
  enum phase: [:planeación, :inicio, :final]
  belongs_to :repository
  belongs_to :user
  has_many :references, inverse_of: :project
  accepts_nested_attributes_for :references, reject_if: :all_blank, allow_destroy: true

  validates :name, :url, :category, :repository, :about, :phase, :introduction, :conclusion, presence: true
  validates :url, :format => URI::regexp(%w(http https))

  # scope :planning_phase, -> { where(phase: 'planeación') }

end

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :project, inverse_of: :references
end

app/models/repository.rb
class Repository < ApplicationRecord
  belongs_to :user
  has_one :project
  has_many :issues
  has_many :branches
  has_many :collaborations
  has_many :users, through: :collaborations

  scope :popular, -> { order(stars: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable

  has_many :repositories, dependent: :delete_all
  has_many :collaborations, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :issues, dependent: :delete_all
  has_many :projects

  validates :username, uniqueness: true, presence: true

  private

  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    return merge_accounts(user, auth) if user && user.confirmed_at

    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.username = auth.info.nickname
      user.login = auth.info.nickname
      user.location = auth.extra.raw_info.location
      user.password = Devise.friendly_token[0,20]
      user.skip_confirmation!
      user.save!
    end
  end

  def self.merge_accounts(user, auth)
    user.provider = auth.provider
    user.uid = auth.uid
    user.username = auth.info.nickname
    user.login = auth.info.nickname
    user.location = auth.extra.raw_info.location
    user.save!
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token, if: :json_request?
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    profile_path(resource.login || resource.username)
  end

  def json_request?
    request.format.json?
  end

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    ApplicationJob.perform_now(@user) if @user.repositories.count == 0
    sign_in_and_redirect @user
  end
end

app/controllers/discourse_controller.rb
require 'single_sign_on'

class DiscourseController < ApplicationController
  before_action :authenticate_user!
  def sso
    secret = "codeando_mexico_sso"
    sso = SingleSignOn.parse(request.query_string, secret)
    sso.email = current_user.email # from devise
    sso.name = current_user.login # this is a custom method on the User class
    sso.external_id = current_user.id # from devise
    sso.sso_secret = secret
    redirect_to sso.to_url("http://159.203.102.53:9000/session/sso_login")
  end
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  def payload
    @params = params[:issue]
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = current_user.repositories.find(params[:repository_id]).issues.open
  end

  def show
    @issue = current_user.repositories.find(params[:repository_id]).issues.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:profile, :repository]

  def index
  end

  def public_profile
    @user = User.find_by(username: params[:username])
  end

  def profile
    @name = get_showable_name
    @repos = current_user.repositories.popular.first(6)
  end

  def marketplace
    @projects = Project.all
  end

  private

  def get_showable_name
    current_user.login || current_user.username || current_user.email
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = current_user.projects.build
    @user_repositories = current_user.repositories
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to project_path @project
    else
      redirect_to new_project_path
    end
  end

  def show
  end

  private

  def project_params
    params.require(:project).permit(:name, :url, :category, :repository_id, :about, :phase, :introduction, :conclusion, references_attributes: [:id, :url, :_destroy])
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @repositories = current_user.repositories
  end

  def show
    @repository = current_user.repositories.find(params[:id])
    @issues = @repository.issues
  end

  def scoped_repositories
    @repositories = User.find_by(username: params[:username]).repositories
  end

  def show_scoped_repositories
    @repository = User.find_by(username: params[:username]).repositories.find_by(name: params[:repository])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def options_for repositories
    options_for_select repositories.map { |repo| [repo.name, repo.id] }
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/projects/_form.html.erb
<div class="container">
  <p>Crea un proyecto nuevo</p>
  <%= form_for @project do |f| %>
    <div class="row">
      <%= f.label :nombre %>
      <%= f.text_field :name %>
    </div>
    <div class="row">
      <%= f.label :URL %>
      <%= f.text_field :url %>
    </div>
    <div class="row">
      <%= f.label :categoría %>
      <%= f.select :category, collection: Project.categories.keys.to_a %>
    </div>
    <div class="row">
      <p>Liga tu proyecto con un repositorio</p>
      <div class="row">
      </div>
      <div class="row">
        <%= f.select :repository_id, options_for(@user_repositories) %>
      </div>
    </div>
    <div class="row">
      <%= f.label :acerca %> <br>
      <%= f.text_area :about %>
    </div>
    <div class="row">
      <%= f.label :fase %>
      <%= f.select :phase, collection: Project.phases.keys.to_a %>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.label :introducción %>
        <%= f.date_field :introduction %>
      </div>
      <div class="col-md-6">
        <%= f.label :conclusión %>
        <%= f.date_field :conclusion %>
      </div>
    </div>
    <div class="row">
      <%= f.fields_for :references do |reference| %>
        <%= render 'reference_fields', f: reference %> <br>
      <% end %>
      <%= link_to_add_association 'Agregar referencia', f, :references %>
    </div>
    <div class="row">
      <%= f.submit 'Crear Proyecto' %>
    </div>
  <% end %>
</div>

app/views/projects/_reference_fields.html.erb
<%= f.text_field :url %>
<%= link_to_remove_association "Quitar referencia", f %>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/repositories/index.html.erb
<p>Encontramos <%= @repositories.count %> repoitorios públicos:</p>
<ul>
  <% @repositories.each do |repo| %>
    <li><%= link_to repo.name.titleize, repository_path(repo) %></li>
  <% end %>
</ul>

app/views/repositories/scoped_repositories.html.erb
<% @repositories.each do |repo| %>
  <p><%= link_to repo.name, scoped_repository_path repo %></p>
<% end %>

app/views/repositories/show.html.erb
<h3><%= @repository.name.titleize %></h3>
<h5><%= @repository.description %></h5>
<%= link_to 'Issues', repository_issues_path(@repository) %>

app/views/repositories/show_scoped_repositories.html.erb
<div class="container">
  <div class="row">
    <h1><%= @repository.name.titleize %></h1>    
  </div>
  <div class="col-md-6">
    <h3>Stars: <%= @repository.stars %></h3>
  </div>
  <div class="col-md-6">
    <h3><%= @repository.description %></h3>
  </div>
</div>