config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks' }
  root 'pages#index'
  get 'discourse/sso', to: 'discourse#sso'

  resources :repositories, only: [:index, :show] do
    resources :issues, only: [:index, :show] do
      resources :comments, only: :index
    end
  end

  resources :projects

  get '/marketplace', to: 'pages#marketplace', as: 'marketplace'
  get '/u/:username', to: 'pages#public_profile', as: 'public_profile'
  get '/u/:username/repositories', to: 'repositories#scoped_repositories', as: 'scoped_repositories'
  get '/u/:username/:repository', to: 'repositories#show_scoped_repositories', as: 'scoped_repository'
  get '/settings/profile', to: 'pages#profile', as: 'profile'
  post '/payload', to: 'github#payload', as: 'payload'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :repository
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :user
  belongs_to :repository
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :issue, optional: true
  belongs_to :user, optional: true
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :repository
  belongs_to :user, optional: true
  has_many :comments
  scope :open, -> { where(state: 'open') }
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :projects
  acts_as_taggable
end

app/models/project.rb
class Project < ApplicationRecord
  enum category: [:op1, :op2, :op3]
  enum phase: [:planeación, :inicio, :final]
  belongs_to :repository
  belongs_to :user
  has_many :references, inverse_of: :project
  accepts_nested_attributes_for :references, reject_if: :all_blank, allow_destroy: true

  validates :name, :url, :category, :repository, :about, :phase, :introduction, :conclusion, presence: true
  validates :url, :format => URI::regexp(%w(http https))

  # scope :planning_phase, -> { where(phase: 'planeación') }

end

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :project, inverse_of: :references
end

app/models/repository.rb
class Repository < ApplicationRecord
  belongs_to :user
  has_one :project
  has_many :issues
  has_many :branches
  has_many :collaborations
  has_many :users, through: :collaborations

  scope :popular, -> { order(stars: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable

  has_many :repositories, dependent: :delete_all
  has_many :collaborations, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :issues, dependent: :delete_all
  has_many :projects

  validates :username, uniqueness: true, presence: true

  private

  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    return merge_accounts(user, auth) if user && user.confirmed_at

    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.username = auth.info.nickname
      user.login = auth.info.nickname
      user.location = auth.extra.raw_info.location
      user.password = Devise.friendly_token[0,20]
      user.skip_confirmation!
      user.save!
    end
  end

  def self.merge_accounts(user, auth)
    user.provider = auth.provider
    user.uid = auth.uid
    user.username = auth.info.nickname
    user.login = auth.info.nickname
    user.location = auth.extra.raw_info.location
    user.save!
    return user
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    ApplicationJob.perform_now(@user) if @user.repositories.count == 0
    sign_in_and_redirect @user
  end
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  def payload
    @params = params[:issue]
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = current_user.repositories.find(params[:repository_id]).issues.open
  end

  def show
    @issue = current_user.repositories.find(params[:repository_id]).issues.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:profile, :repository]

  def index
  end

  def public_profile
    @user = User.find_by(username: params[:username])
  end

  def profile
    @name = get_showable_name
    @repos = current_user.repositories.popular.first(6)
  end

  def marketplace
    @projects = Project.all
  end

  private

  def get_showable_name
    current_user.login || current_user.username || current_user.email
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = current_user.projects.build
    @user_repositories = current_user.repositories
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to project_path @project
    else
      redirect_to new_project_path
    end
  end

  def show
  end

  private

  def project_params
    params.require(:project).permit(:name, :url, :category, :repository_id, :about, :phase, :introduction, :conclusion, references_attributes: [:id, :url, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def options_for repositories
    options_for_select repositories.map { |repo| [repo.name, repo.id] }
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeandomexico</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Un espacio de innovación abierta de interacción entre organizaciones de la Sociedad Civil y la comunidad tecnológica para proponer soluciones a temas cívicos.">
    <meta name="keywords" content="hacking cívico, codeando méxico, innovación abierta , sociedad civil, comunidades">
    <meta name="author" content="Comunidad de Codeando México">

    <title>Codeando México</title>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<body>
    <!-- Page Header -->
    <div class="navbar navbar-inverse">
      <div class="row">
        <div class="container">
          <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, method: 'delete' %>
          <% else %>
            <%= link_to 'Log in', new_user_session_path %>
          <% end %>
        </div>
      </div>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="https://codeandomexico.org"><%= image_tag('logo.png')%></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right quitar-respo">
                    <li class="facebook">
                        <a href="https://www.facebook.com/CodeandoMexico/" target="_blank">
                            <%= image_tag('face.png') %>
                        </a>
                        <span>Facebook</span>
                    </li>
                    <li class="twitter">
                        <a href="https://twitter.com/codeandomexico" target="_blank">
                            <%= image_tag('twitter.png') %>
                        </a>
                        <span>Twitter</span>
                    </li>
                    <li class="github">
                        <a href="https://github.com/CodeandoMexico" target="_blank">
                            <%= image_tag('github.png') %>
                        </a>
                        <span>Github</span>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right aparecer-respo">
                    <li>Proyectos abiertos</li>
                    <li>Participa</li>
                    <li>Comunidad</li>
                    <li>Nuestro propósito</li>
                    <li>Newsletter</li>
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.container -->
    </div><!--/.navbar -->

    <div class="wide">
        <h1 class="title">Tecnología de hoy para la ciudadanía de mañana</h1>
        <h2 class="sub-title">Codeando México es una comunidad que busca desarrollar tecnología para construir un mejor país.</h2>
    </div>
    <!-- /.end Page Header -->
    <div class="clearfix"></div>

    <!-- Section: ¿Qué hacemos? -->
    <section id="about">
        <div class="container">
            <div id="what-do">
                <div class="col-xs-12 container-texto">
                    <div class="col-md-4"><p class="parrafo">¿QUÉ HACEMOS A TRAVÉS DE LA TECNOLOGÍA?</p></div>
                    <div class="col-md-8">
                        <div class="col-xs-4 task"><div><hr></div><p>RESOLVER PROBLEMAS PÚBLICOS Y SOCIALES</p></div>
                        <div class="col-xs-4 task"><div><hr></div><p>GENERAR NUEVAS FORMAS DE PARTICIPACIÓN CÍVICA</p></div>
                        <div class="col-xs-4 task"><div><hr></div><p>REFORMULAR LA RELACIÓN ENTRE GOBIERNO Y CIUDADANÍA</p></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Section: Proyectos -->
    <div id="proyectos-codeando" class="container">
        <div class="text-center">
            <h3>Proyectos Abiertos</h3>
        </div>
        <div class="col-xs-12 proyectos">
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6">
                <a href="https://mapaton.org/" target="_blank">
                    <div class="box">
                        <div class="box-content">
                            <div class="hover-shadow"></div>
                            <%= image_tag('project1.png') %>
                            <h4>MapMap</h4>
                            <p><span>6</span> participantes</p>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
                                    <span class="sr-only">100% Complete</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6">
                <a href="http://www.informebajolupa.mx/" target="_blank">
                    <div class="box">
                        <div class="box-content">
                            <div class="hover-shadow"></div>
                            <%= image_tag('project2.png') %>
                            <h4>Informe Bajo Lupa</h4>
                            <p><span>10</span> participantes</p>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%">
                                    <span class="sr-only">40% Complete</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 margen-respo">
                <a href="http://datamx.io/" target="_blank">
                    <div class="box">
                        <div class="box-content">
                            <div class="hover-shadow"></div>
                            <%= image_tag('project3.png') %>
                            <h4>Datamx</h4>
                            <p><span>21</span> participantes</p>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width:90%">
                                    <span class="sr-only">90% Complete</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 margen-respo">
                <a href="https://codeandomexico.org/retos/">
                    <div class="box">
                        <div class="box-content">
                            <div class="hover-shadow"></div>
                            <%= image_tag('project4.png') %>
                            <h4 class="otro-padding">Explora más proyectos</h4>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>

    <!-- Section: Proyectos -->
    <div class="container">
        <div class="text-center">
            <h3 class="other-margin-top">Participa</h3>
        </div>
        <div class="col-xs-12 participacion">
            <div class="col-lg-5 col-md-4 col-sm-4 col-xs-12">
                <div class="user">
                    <%= image_tag('participa1.png', class: 'img-circle') %>
                </div>
            </div>
            <div class="col-lg-7 col-md-8 col-sm-8 col-xs-12">
                <h3 class="text-bold">Involúcrate</h3>
                <ul>
                    <li><span></span>Organiza o asiste a una noche de hacking cívico.</li>
                    <li class="active"><span class="active"></span>Documenta un proyecto  &lt;<a href="https://github.com/CodeandoMexico" target="_blank">Github</a>&gt;</li>
                    <li><span></span>Identifica un problema en tu comunidad. &lt;<a href="https://codeandomexico.org/lanza-un-reto">Formulario</a>&gt;</li>
                </ul>
            </div>
            <div class="clearfix"></div><br>
            <div class="col-lg-5 col-md-4 col-sm-4 col-xs-12">
                <div class="user">
                    <%= image_tag('participa2.png', class: 'img-circle') %>
                </div>
            </div>
            <div class="col-lg-7 col-md-8 col-sm-8 col-xs-12">
                <h3 class="text-bold">Construye</h3>
                <ul>
                    <li><span></span>Abre un conjunto de datos &lt;<a href="http://datamx.io/" target="_blank">Datamx</a>&gt;</li>
                    <li><span></span>Contribuye a un proyecto existente  &lt;<a href="https://github.com/CodeandoMexico" target="_blank">Github</a>&gt;</li>
                    <li><span></span>Propón un proyecto nuevo &lt;<a href="https://codeandomexico.org/lanza-un-reto">Formulario</a>&gt;</li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Section: Hackers -->
    <section class="container-hackers ">
        <div class="col-xs-12 no-padding">
            <div class="col-md-6 izq no-padding container-fluid">
                <h2>HACKERS CONSTRUYENDO UN MEJOR PAÍS</h2>
                <h3>Somos una comunidad abierta y orientada a la acción. Colaboramos en la construcción herramientas que resuelvan problemas públicos y sociales.</h3>
                <h4>MISIÓN _</h4>
                <p>Desarrollar tecnología para <span>construir un mejor país.</span></p>
            </div>
            <div class="col-md-6 der no-padding"></div>
        </div>
    </section>

    <!-- Section: Propósito -->
    <div class="container">
        <div class="text-center proposito">
            <h3 class="other-margin-top">Nuestro propósito</h3>
            <p>Codeando México es una comunidad tecnológica que busca desarrollar tecnología para construir un mejor país de manera abierta y colaborativa.</p>
            <a href="https://codeandomexico.org/registrate" class="btn unete">Únete</a>
            <h4 class="text-bold">Creemos en el potencial de la tecnología para:</h4>
                <ul class="no-point">
                    <li>&lt;<span class="circulo"> RESOLVER PROBLEMAS PÚBLICOS Y SOCIALES </span>&gt;</li>
                    <li>&lt;<span class="circulo change-color"> GENERAR NUEVAS FORMAS DE PARTICIPACIÓN CÍVICA </span>&gt;</li>
                    <li>&lt;<span class="circulo"> REFORMULAR LA RELACIÓN ENTRE GOBIERNO Y CIUDADANÍA </span>&gt;</li>
                </ul>
        </div>
    </div>

    <!-- Section: Newsletter -->
    <section class="container-newsletter">
        <div class="container">
            <div class="text-center newsletter">
                <h3 class="other-margin-top">Newsletter</h3>
                <p>¿Te interesa conocer más de nosotros? Suscríbete a nuestro boletín mensual &lt;<span class="color-red">equipo@codeandomexico.org</span>&gt;</p>
                <div class="container-form">
                    <form action="#">
                        <div class="input-group">
                            <input class="btn" name="email" id="email" type="email" placeholder="E-mail" required>
                            <button class="btn btn-info" type="submit">¡Suscríbete!</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="https://codeandomexico.org"><%= image_tag('logo.png') %></a>
                <div class="menu-bottom">
                    <ul>
                        <li>Proyectos abiertos</li>
                        <li>Participa</li>
                        <li>Comunidad</li>
                        <li>Nuestro propósito</li>
                        <li>Newsletter</li>
                    </ul>
                </div>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="facebook">
                        <a href="https://www.facebook.com/CodeandoMexico/" target="_blank">
                            <%= image_tag('face.png', class: 'img-circle') %>
                        </a>
                        <span>Facebook</span>
                    </li>
                    <li class="twitter">
                        <a href="https://twitter.com/codeandomexico" target="_blank">
                            <%= image_tag('twitter.png', class: 'img-circle') %>
                        </a>
                        <span>Twitter</span>
                    </li>
                    <li class="github">
                        <a href="https://github.com/CodeandoMexico" target="_blank">
                            <%= image_tag('github.png', class: 'img-circle') %>
                        </a>
                        <span>Github</span>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
            <p class="text-left ajuste-texto-2">2017 | Creado por la comunidad de <a href="http://codeandoxalapa.org/" target="_blank">Codeando Xalapa</a> con <span class="glyphicon glyphicon-heart color-green"></span>.</p>
        </div><!--/.container -->
    </footer>

    <!-- Google Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-36672089-6', 'codeandomexico.org');
        ga('send', 'pageview');
    </script>

</body>

</html>

app/views/pages/marketplace.html.erb
<% @projects.each do |p| %>
  <%= p.name %>
<% end %>

app/views/pages/profile.html.erb
<div class="row">
  <div class="container">
    <% if user_signed_in? %>
      <%= link_to 'Salir', destroy_user_session_path, method: 'delete' %>
      <%= link_to 'Editar mi cuenta', edit_user_registration_path %>
    <% else %>
      <%= link_to 'Log in', new_user_session_path %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="container">
    <h3>Hola, <%= @name %></h3>
    <% if current_user.repositories.count == 0 %>
      <p>No tienes repositorios, quieres sincronizarte con tu cuenta de github? </p>
      <%= link_to 'Sí, quiero sincronizar mi cuenta de github', omniauth_authorize_path(:user, :github) %>
    <% else %>
      <%= link_to 'Repositorios', repositories_path %>
    <% end %>
    <br>
    <% @repos.each do |repo| %>
      <%= repo.name %> <br>
    <% end %>
  </div>
</div>

app/views/pages/public_profile.html.erb
<%= @user.email %>

app/views/pages/repository.html.erb
<p>Nombre: <%= @repo.name %></p>
<p>Descripción: <%= @repo.description %></p>
<p>Lenguaje: <%= @repo.language %></p>
<p>Estrellas: <%= @repo.stargazers_count %></p>
<% if @issues.length > 0 %>
  <p>Issues Abiertas: <%= @repo.open_issues %></p>
  <% @issues.each do |issue| %>
    <p>Issue #<%= issue.number %> | <%= issue.title %></p>
  <% end %>
<% else %>
  <p>No hay Issues en este repositorio</p>
<% end %>